import "../../../css/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogLayout({
  children,
  introduction,
}: {
  children: React.ReactNode;
  introduction: React.ReactNode;
}) {
  return (
    <div className="flex">
      <div className="w-4/5">{children}</div>
      <div className="w-1/5">{introduction}</div>
    </div>
  );
}
